New feature: Jump directly to a knot.
deep-entertainment/escoria-ink-bridge pull request #2
Opened 2023-09-12 16:09 UTC by cidneyhamilton

Supports the following syntax in .esc files to jump directly to a knot in the script.

`play_ink res://path/to/ink/script.ink.json knot_name` 

If the second parameter is blank, the script will start from the top.

There's a new button in the test scene to test it out.

2023-09-12 18:48 UTC, dploeger requested changes
Some small remarks

2023-09-12 18:48 UTC, dploeger commented on addons/escoria-ink-bridge/api/escoria_ink_bridge.gd
> +func run_story(ink_file: String, knot: String):
Add a default value (, knot := "") for knot here to make it backwards compatible.

2023-09-12 18:48 UTC, dploeger commented on script_templates/ink_template.gd
Do you know where those script templates come from? Are they generated by inkgd? Maybe we can get rid of them in the repository.

2023-09-13 17:16 UTC, cidneyhamilton commented on script_templates/ink_template.gd
Adding to .gitignore to keep them out of the repository.

2023-09-13 17:17 UTC, cidneyhamilton commented
Fixes in (and new commits squashed).

2023-09-15 12:21 UTC, cidneyhamilton commented on script_templates/ink_template.gd
(and yep, it's all been generated.) I'm erring on the side of not making changes unless specified.

2023-09-15 12:24 UTC, dploeger approved these changes
Awesome! Thanks a lot. 🎁

2023-09-15 12:24 UTC, merged